[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Added to copy MyStruct[] memory into storage
via_ir = false

# fix the compiler version to standardize testing
solc_version = "0.8.28"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
